- hosts: "{{ maszyna }}"
  vars:
    apka: "{{ app }}"
    maszyna: "{{ cel }}"
  tasks:
  - name: Install package {{ apka }}
    apt: name={{ apka }} state=latest update_cache=true
#### ansible-playbook -i homelab_inv install_soft_vars.yml --extra-vars "app=iftop cel=ansible.lan"
